# Generated by Django 5.0 on 2024-01-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('kelas', models.CharField(blank=True, max_length=50)),
                ('jurusan', models.CharField(blank=True, max_length=50)),
                ('subjurusan', models.CharField(blank=True, max_length=10)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=50)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('angkatan', models.CharField(blank=True, max_length=10)),
                ('kontak', models.CharField(blank=True, max_length=10)),
                ('ttl', models.DateField(blank=True)),
                ('nis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
