# Generated by Django 5.0.1 on 2024-01-07 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_answer_post_alter_reply_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_at',
            new_name='at',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='content_answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_post',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_at',
            new_name='at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='content_reply',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
