# Generated by Django 5.0.1 on 2024-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_answer_user_alter_reply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default='shared'),
        ),
    ]
