# Generated by Django 5.0.1 on 2024-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_remove_likepost_post_remove_likepost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likeu',
            field=models.ManyToManyField(related_name='likeu', to='posts.post'),
        ),
    ]
