# Generated by Django 5.0.1 on 2024-03-27 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(db_column='username', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
