
import type { Metadata } from 'next'
import './globals.css'
import { poppins } from '@/app/ui/fonts';
import Navbar from './ui/navigation/navbar';
import LoginForm from './ui/auth/login-form';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body>
        <nav>
          <Navbar />
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
