# Generated by Django 5.0.1 on 2024-01-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('nis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nis', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('bio', models.CharField(blank=True, max_length=50)),
                ('kelas', models.CharField(blank=True, max_length=50)),
                ('jurusan', models.CharField(blank=True, max_length=50)),
                ('subjurusan', models.CharField(blank=True, max_length=10)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=50)),
                ('alamat', models.CharField(blank=True, max_length=200)),
                ('angkatan', models.CharField(blank=True, max_length=10)),
                ('kontak', models.CharField(blank=True, max_length=10)),
                ('ttl', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
