# Generated by Django 4.2.9 on 2024-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_nis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ttl',
            field=models.DateField(blank=True, null=True),
        ),
    ]
